import { createReducerSagaIdentify } from 'utils/createReducerSagaIdentify';

export const REDUCER_SAGA_IDENTIFY = createReducerSagaIdentify(module);

enum DASHBOARD_REDUCER_KEY {
    SET_STRING = 'DASHBOARD_REDUCER_KEY@@SET_STRING',
    SET_STRING_SUCCESS = 'DASHBOARD_REDUCER_KEY@@SET_STRING_SUCCESS',
    GET_WEATHER_FORCAST = 'DASHBOARD_REDUCER_KEY@@GET_WEATHER_FORCAST',
    GET_WEATHER_FORCAST_SUCCESS = 'DASHBOARD_REDUCER_KEY@@GET_WEATHER_FORCAST_SUCCESS',
    GET_WEATHER_FORCAST_FAIL = 'DASHBOARD_REDUCER_KEY@@GET_WEATHER_FORCAST_FAIL',
}
export { DASHBOARD_REDUCER_KEY };
