name: CI

on: [pull_request]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js 12.x
              uses: actions/setup-node@v1
              with:
                  node-version: '12.x'
            - run: npm install
            - run: npm test
              continue-on-error: true
              env:
                  CI: true
                  NODE_ENV: 'production'
            - run: npm run build
              env:
                  CI: true
                  NODE_ENV: 'production'
            - name: Upload coverage to Codecov
              uses: codecov/codecov-action@v1
              with:
                  directory: ./coverage/jest/
                  flags: unittests
                  name: codecov
                  verbose: true
