on:
  release:
    types: [created]

env:
  NODE_VERSION: '12.x'                # set this to the node version to use
  AZURE_STORAGE_CONNECTION_STRING: '${{ secrets.STAGING_AZURE_BLOB }}'

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repo
      uses: actions/checkout@v2
    
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}
    
    - name: npm install, build
      run: |
        # Build the project, then
        # deploy to Azure Web App.
        npm install
        npm run build
    
    - name: Publish app
      uses: Azure/cli@v1.0.0
      with:
        azcliversion: latest
        inlineScript: |
          az storage blob delete-batch -s \$web
          az storage blob upload-batch -s $GITHUB_WORKSPACE/build -d \$web
